# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# =============================
# Site-wide settings
# =============================
locale: "en-US"
title: "Abolfazl (Arash) Sodagartojgi"
title_separator: "-"
name: "Abolfazl (Arash) Sodagartojgi"
description: "PhD Candidate in Statistics at Rutgers University — Statistical Machine Learning, High-Dimensional Inference, Generative Models"
# Your GitHub Pages URL (project site)
# Your GitHub Pages URL (user site)
url: "https://sodagar1374.github.io"
baseurl: ""        # must stay empty for a user site
repository: "sodagar1374/sodagar1374.github.io"



# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
# =============================
# Theme & plugins
# =============================
remote_theme: "mmistakes/minimal-mistakes"
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# Pagination (for blog/news)
paginate: 5
paginate_path: "/page:num/"

# =============================
# Author profile (sidebar card)
# =============================
author:
  name: "Abolfazl (Arash) Sodagartojgi"
  avatar: "/images/profile.jpg"        # add your photo at /images/profile.jpg
  bio: "PhD Candidate in Statistics at Rutgers University. Research: dynamic factor models, sparse state-space inference, deep generative models, causal inference in finance & healthcare, and stochastic weather generators."
  location: "Highland Park, NJ"
  email: "sodagaax@gmail.com"
  github: "sodagar1374"
  linkedin: "abolfazl-arash-sodagartojgi-728050156"
  scholar: "l0vfBEwAAAAJ"
  orcid: ""                            # fill if you have one
  # Optional: twitter: "yourhandle"

# =============================
# Defaults for pages & posts
# =============================
defaults:
  # All regular pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

  # Blog posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: false

  # Collections below (teaching, talks, publications, portfolio)
  - scope:
      path: ""
      type: "teaching"
    values:
      layout: "single"
      author_profile: true
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "single"
      author_profile: true
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "single"
      author_profile: true
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "single"
      author_profile: true

# =============================
# Collections (enable these folders)
# =============================
collections:
  teaching:
    output: true
    permalink: /teaching/:path/
  talks:
    output: true
    permalink: /talks/:path/
  publications:
    output: true
    permalink: /publications/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/

# =============================
# Social links in footer
# =============================
footer:
  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=l0vfBEwAAAAJ"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sodagar1374"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/abolfazl-arash-sodagartojgi-728050156/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:sodagaax@gmail.com"

# =============================
# SEO & analytics (optional)
# =============================
# google_analytics: "G-XXXXXXXXXX"

# Build exclusions (leave as-is)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
